name: Test Profile Script

on: [push, pull_request]

# TODO: we have a bug on setting shell name in jobs https://github.com/actions/runner/issues/444

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [bash, zsh]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: ubuntu-latest
            shell: zsh
          - os: macos-latest
            shell: bash
          - os: macos-latest
            shell: zsh

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up shell
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y bash zsh make

      - name: Set up shell
        if: matrix.os == 'macos-latest'
        run: brew install bash zsh make

      - name: Set up shell environment
        run: |
          cp profile.sh $HOME/.profile.sh 
          echo "source $HOME/.profile.sh" >> ~/.${{ matrix.shell }}rc
          source ~/.${{ matrix.shell }}rc
          profile update 
          profile i test_profile 
          profile l 
          profile e test_profile 
          profile s 
          profile pre 
          profile post 
          profile test_profile 
          profile h 