name: Test Profile Script

on: [push, pull_request]

# TODO: we have a bug on setting shell name in jobs https://github.com/actions/runner/issues/444

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [bash, zsh]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: ubuntu-latest
            shell: zsh
          - os: macos-latest
            shell: bash
          - os: macos-latest
            shell: zsh

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up shell
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y bash zsh make

      - name: Set up shell
        if: matrix.os == 'macos-latest'
        run: brew install bash zsh make

      - name: Set up shell environment
        run: |
          cp profile.sh $HOME/.profile.sh 
          echo "source $HOME/.profile.sh" >> ~/.${{ matrix.shell }}rc
          source ~/.${{ matrix.shell }}rc

      - name: Test profile update
        shell: bash
        run: |
          profile update 

      - name: Test profile init
        shell: bash
        run: |
          profile i test_profile 

      - name: Test profile list
        shell: bash
        run: |
          profile l 

      - name: Test profile edit
        shell: bash
        run: |
          profile e test_profile 

      - name: Test profile sync
        shell: bash
        run: |
          profile s 

      - name: Test profile pre
        shell: bash
        run: |
          profile pre 

      - name: Test profile post
        shell: bash
        run: |
          profile post 

      - name: Test profile load
        shell: bash
        run: |
          profile test_profile 

      - name: Test profile help
        shell: bash
        run: |
          profile h 